name: Android Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app/Android

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List APK Output
        run: |
          echo "📂 APK Files:"
          find app/build/outputs -name "*.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aditya-HUD-APK
          path: app/Android/app/build/outputs/apk/debug/*.apk
